### PR TITLE
Updated to 1.3-Beta

### PR DESCRIPTION
**Pull request by TyoAtrosa**

### CODE REVIEW

**Review by lambui — APPROVED** [review]

**Comment by lambui** [comment]
Hi can you compile and provide a new release archive so I can upload it too. Thank for maintaining this mod 👍

**Comment by TyoAtrosa** [comment]
I have one uploaded under releases on my fork already, is that what you mean? I'm very new to Github.

**Comment by lambui** [comment]
Ok then can I take that release on your fork and upload it here?

**Comment by TyoAtrosa** [comment]
yeah that's fine. btw, mine is based on cragrims fork as far as the map itself goes, and has his optional farm cave as a config option. so you may want to change the maps out in the archive.

**Comment by lambui** [comment]
Alright thanks. I will remove the assets folder in the archive and release it as 2.0.3 official version.

**Comment by TyoAtrosa** [comment]
ok, just keep in mind i changed it to load the maps from the assets folder as XNB replacements are not recommended anymore.

**Comment by lambui** [comment]
Thanks for letting me know. I have recorded all the changes of new version in README file. Please take a look if I miss anything.

**Comment by TyoAtrosa** [comment]
you may want to include that the optional farm cave is enabled by default, so players will want to put there FarmCave.xnb in the assets folder unless they disable it in the config.

**Comment by TyoAtrosa** [comment]
I probably should've thought about that before i compiled it...

**Comment by lambui** [comment]
It's fine. Can you tell me how to disable it in config? I don't have SMAPI running so I can't compile it myself to look at the config file. I will add that in the README.

**Comment by TyoAtrosa** [comment]
just change "useOptionalCave": to false. it's the first config option in the source as well if you want to recompile it as well.

**Comment by lambui** [comment]
Alright thanks. I have put everything in README. Everything should be good now

**Pull request merged**
